### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by nixiaoyu** [yairf11/MUPPET#3]
When processing Wikipedia:
`python hotpot/scripts/retriever/build_tfidf.py data/db/wiki_hotpot_sentences_v1.1.db data/db/ --num-workers 4
`
I get the following traceback:

> 12/26/2020 03:54:16 AM: [ Counting words... ]
> 12/26/2020 03:54:22 AM: [ Mapping... ]
> 12/26/2020 03:54:22 AM: [ -------------------------Batch 1/11------------------------- ]
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/niyihan/anaconda3/envs/MUPPET/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "hotpot/scripts/retriever/build_tfidf.py", line 72, in count
>     tokens = tokenize(' '.join(fetch_sentences(doc_title)))
>   File "hotpot/scripts/retriever/build_tfidf.py", line 59, in tokenize
>     return PROCESS_TOK.tokenize(text)
>   File "/home/niyihan/MUPPET/hotpot/tokenizers/corenlp_tokenizer.py", line 107, in tokenize
>     output = json.loads(output[start:].decode('utf-8')) 
>   File "/home/niyihan/anaconda3/envs/MUPPET/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/home/niyihan/anaconda3/envs/MUPPET/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/niyihan/anaconda3/envs/MUPPET/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "hotpot/scripts/retriever/build_tfidf.py", line 184, in <module>
>     count_matrix, doc_dict = get_count_matrix()
>   File "hotpot/scripts/retriever/build_tfidf.py", line 115, in get_count_matrix
>     for b_row, b_col, b_data in workers.imap_unordered(_count, batch):
>   File "/home/niyihan/anaconda3/envs/MUPPET/lib/python3.6/multiprocessing/pool.py", line 735, in next
>     raise value
> json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

@yairf11 Is the json data format of some file wrong, or something wrong with CoreNLP?

I am looking forward to your reply and thank you very much!

**Comment by yairf11** [comment]
I can't say for sure. Is your CoreNLP version 3.8.0?

**Comment by nixiaoyu** [comment]
Oh, I see. I have multiple versions of CoreNlP and the CLASSPATH may be confused. Now I changed the CLASSPATH to only one version, and it's ok now. Thank you very much!

**Comment by nixiaoyu** [comment]
I have run to the last step 

`python hotpot/scripts/train_eval/hotpot_qa_distractors_eval.py models/hotpot-qa-model qa_pred.json -s latest -c retrieval_file -t 600 --input_file out/n2-64/n1-32/n1-32_n2-64_k1-8_k2-45.json --test_mode`

but got another error:

> Setting up model
> Had pre-trained word embeddings for 331543 of 511556 words
> Restoring variables
> Restoring EMA variables
> Begin evaluation
> Saving result
> Traceback (most recent call last):
>   File "hotpot/scripts/train_eval/hotpot_qa_distractors_eval.py", line 514, in <module>
>     main()
>   File "hotpot/scripts/train_eval/hotpot_qa_distractors_eval.py", line 510, in main
>     df_to_pred(df, output_file)
>   File "/home/niyihan/MUPPET/hotpot/scripts/train_eval/ranked_scores_to_hotpot_pred.py", line 22, in df_to_pred
>     max_span_question_score = group[span_q_col].expanding().apply(lambda x: x.max(), raw=True).values
> TypeError: apply() got an unexpected keyword argument 'raw'

It seems that there is something wrong for pandas, but I have tried different versions of pandas and even numpy, they all didn't work. @yairf11 Have you ever met this error? Thank you very much!

**Comment by yairf11** [comment]
Can you please check whether upgrading to `pandas>=0.23` helps?

**Comment by nixiaoyu** [comment]
Okay, I upgrade to pandas 0.23 and it works. In addition, I found that directly removing 'raw=True' is all right as well. Thank you very much!
